---
title: "Méthodes pour la détéction des agroforesteries cacaoyères sans échantillons terrain ni machine learning"
format: html
author: Rodrigue da Silva
---
# Mes analyses
## Méthode 1: Mosaïque et K-means sur GEE

Le Tri-National de la Sangha se trouvant en région tropicale humide, les images satellitaires propres sans perturbations atmosphériques sont difficilement accessibles et même agglomérer les images Landsat ou Sentinel-2 avec un couvert nuageux faible de moins de 30% sur 1 an ne couvre pas tout le territoire forestier. Il faut ajouter à cela que le cacao dans le TNS pousse sous canopée dans des petites exploitations familiales et qu'il est donc difficilement repérable. En l'absence d'un nombre suffisant de champs de cacao pour permettre une détection par machine learning, et après de nombreux tests sur des données images, la première méthode a été de mosaïquer les images Landsat du territoire sur 1 an et demi puis découper l'image obtenue. On a ainsi divisé le TNS en 48 entités en fonction des coutures (discontinuités dues aux conditions de prise des images) afin d'effacer cet obstacle à l'identification du cacao.
Compte tenu de la mauvaise connaissance du territoire, c'est le K-means qui a été choisi pour partager les images en 20 classes du sol. Un nombre plus grand de couches pourrait être envisagé car toutes les parties du TNS n'ont pas la même amplitude QGIS ne supportant pas les opérations trop lourdes, les étapes sus-mentionnées seront réalsées en JavaScript sur Google Earth Engine:

<script>
// == Imports ==

var zone = table.geometry();


// == Collections Landsat 8/9 ==

var L8 = ee.ImageCollection('LANDSAT/LC08/C02/T1_L2');
var L9 = ee.ImageCollection('LANDSAT/LC09/C02/T1_L2');

var col = L8.merge(L9);


// == Filtrage ==

var images = col
  .filterBounds(zone)
  .filterDate('2025-01-01', '2026-06-01')
  .filter(ee.Filter.lt('CLOUD_COVER', 30));

print('Nombre images :', images.size());


// == Masque de nuages ==

function mask(image) {

  var qa = image.select('QA_PIXEL');

  var mask = qa.bitwiseAnd(1 << 1).eq(0)
    .and(qa.bitwiseAnd(1 << 2).eq(0))
    .and(qa.bitwiseAnd(1 << 3).eq(0))
    .and(qa.bitwiseAnd(1 << 4).eq(0));

  return image.updateMask(mask);
}


// == Scale Factor USGS ==

function scale(image) {

  var optical = image.select([
    'SR_B2',
    'SR_B3',
    'SR_B4',
    'SR_B5',
    'SR_B6',
    'SR_B7'
  ])
  .multiply(0.0000275)
  .add(-0.2);

  return image.addBands(optical, null, true);
}


// == Mosaïque ==

var mosaic = images
  .map(mask)
  .map(scale)
  .median()
  .clip(zone);


// == Bandes K-means ==

var bands = [
  'SR_B2',
  'SR_B3',
  'SR_B4',
  'SR_B5',
  'SR_B6',
  'SR_B7'
];


// == Composition colorée RGB ==

Map.centerObject(table,8);


Map.addLayer(
  mosaic,
  {
    bands:[
      'SR_B4',
      'SR_B3',
      'SR_B2'
    ],
    min:0,
    max:0.3
  },
  'RGB'
);


Map.addLayer(
  table,
  {},
  'Polygones'
);


// == K-MEANS INDÉPENDANTS ==

var nb = table.size().getInfo();

print('Nombre polygones :', nb);


var list = table.toList(nb);



for (var i = 0; i < nb; i++) {


  var feature = ee.Feature(list.get(i));


  var geom = feature.geometry();


  // image locale

  var imgPoly = mosaic.clip(geom);



  // échantillonnage local

  var training = imgPoly
    .select(bands)
    .sample({

      region: geom,

      scale:30,

      numPixels:3000,

      geometries:false

    });



  // K-means propre au polygone

  var clusterer = ee.Clusterer
    .wekaKMeans(20)
    .train(training);



  // classification

  var clustered = imgPoly
    .select(bands)
    .cluster(clusterer)
    .toByte();



  // == Affichage des 48 rasters ==

  Map.addLayer(

    clustered,

    {

      min:0,

      max:19,

      palette:[

        'blue',
        'green',
        'yellow',
        'red',
        'purple',
        'orange',
        'cyan',
        'brown',
        'pink',
        'gray',
        'lime',
        'magenta',
        'teal',
        'navy',
        'white',
        'black',
        'gold',
        'coral',
        'violet',
        'darkgreen'

      ]

    },

    'KMEANS_' + (i+1),

    false

  );



  // == Export Google Drive ==


  Export.image.toDrive({

    image: clustered,

    description:
      'KMEANS_' + (i+1),

    folder:
      'GEE_Exports',

    fileNamePrefix:
      'KMEANS_' + (i+1),

    region:
      geom,

    scale:
      30,

    maxPixels:
      1e13

  });


}
</script>

## Comparaison NIR-classification

Les 48 images sont ensuite extraites de Google Drive pour être traitées dans QGIS: c'est là que l'utilisateur va rassembler les 20 classes. En comparant avec les images NIR (proche-infrarouge) qui distinguent bien l'agroforesterie (ou se trouve le cacao), il pourra trier la ou les classes qui sont le plus susceptibles d'en faire partie.
En période de pluies fortes et de maximum végétatif (fin novembre- fin mars) les agroforêts sous ombrage, plus jeunes émettent fortement dans le proche infrarouge, plus que les forêts mais moins que les cultures à ciel ouvert. En période de déclin végétatif ou de moindres pluies (fin novembre- fin mars) leur réflectance moyenne dans le proche infrarouge les distingue du reste de la végétation et particulièrement des cultures à ciel ouvert qui n'émettent plus dans ces longueurs d'onde. En augmentant les contrastes des images, les agroforêts sous ombrages deviennent évidentes. Le NDVI des agroforêts est aussi plus fort que celui des forêts primaires aux alentours.
